from pathlib import Path
import shlex

from bazzite_mcp.config import load_config
from bazzite_mcp.runner import run_audited, run_command


def _repo_slug() -> str:
    return load_config().repo_slug


def _repo_local() -> str:
    return load_config().repo_local


def _default_branch(repo: str) -> str:
    qrepo = shlex.quote(repo)
    head = run_command(f"git -C {qrepo} symbolic-ref --short refs/remotes/origin/HEAD")
    if head.returncode == 0 and head.stdout.strip():
        remote_ref = head.stdout.strip()
        if "/" in remote_ref:
            return remote_ref.split("/", 1)[1]

    current = run_command(f"git -C {qrepo} branch --show-current")
    if current.returncode == 0 and current.stdout.strip():
        return current.stdout.strip()
    return "main"


def suggest_improvement(
    title: str,
    description: str,
    category: str = "enhancement",
) -> str:
    """Create a GitHub issue suggesting an improvement to bazzite-mcp."""
    labels = {
        "missing-tool": "enhancement,tool-request",
        "bug": "bug",
        "enhancement": "enhancement",
        "docs": "documentation",
        "guardrail": "safety",
    }
    label_str = labels.get(category, "enhancement")
    body = (
        f"**Category:** {category}\n\n{description}\n\n---\n"
        "*Auto-generated by bazzite-mcp self-improvement system*"
    )

    cmd = (
        f"gh issue create --repo {shlex.quote(_repo_slug())} "
        f"--title {shlex.quote(title)} "
        f"--body {shlex.quote(body)} "
        f"--label {shlex.quote(label_str)} 2>&1"
    )
    result = run_audited(
        cmd,
        tool="suggest_improvement",
        args={"title": title, "category": category},
    )
    if result.returncode != 0:
        return (
            "Could not create GitHub issue "
            f"(gh error: {result.stderr or result.stdout}).\n\n"
            "Suggestion recorded locally:\n"
            f"  Title: {title}\n"
            f"  Category: {category}\n"
            f"  Description: {description}"
        )

    return (
        f"Improvement suggested: {result.stdout.strip()}\n\n"
        f"Title: {title}\n"
        f"Category: {category}"
    )


def contribute_fix(branch_name: str, description: str, files_changed: str) -> str:
    """Create branch, commit selected files, push, and open PR."""
    repo = _repo_local()
    qrepo = shlex.quote(repo)
    base_branch = _default_branch(repo)

    current_branch_result = run_command(f"git -C {qrepo} branch --show-current")
    current_branch = current_branch_result.stdout.strip() or base_branch

    create_branch = run_audited(
        f"git -C {qrepo} checkout -b {shlex.quote(branch_name)}",
        tool="contribute_fix",
        args={"branch": branch_name, "description": description[:100]},
    )
    if create_branch.returncode != 0:
        if "already exists" in (create_branch.stderr or "").lower():
            checkout_existing = run_audited(
                f"git -C {qrepo} checkout {shlex.quote(branch_name)}",
                tool="contribute_fix",
                args={"action": "checkout-existing-branch", "branch": branch_name},
            )
            if checkout_existing.returncode != 0:
                return (
                    f"Failed to switch to existing branch: {checkout_existing.stderr}"
                )
        else:
            return f"Failed to create branch: {create_branch.stderr}"

    safe_files_list = shlex.split(files_changed)
    if not safe_files_list:
        run_audited(
            f"git -C {qrepo} checkout {shlex.quote(current_branch)}",
            tool="contribute_fix",
            args={"action": "restore-branch", "branch": current_branch},
        )
        return "Failed to stage files: no files specified."

    safe_files = " ".join(shlex.quote(f) for f in safe_files_list)
    add_result = run_audited(
        f"git -C {qrepo} add {safe_files}",
        tool="contribute_fix",
        args={"action": "git-add", "files": safe_files_list},
    )
    if add_result.returncode != 0:
        run_audited(
            f"git -C {qrepo} checkout {shlex.quote(current_branch)}",
            tool="contribute_fix",
            args={"action": "restore-branch", "branch": current_branch},
        )
        return f"Failed to stage files: {add_result.stderr}"

    commit = run_audited(
        f"git -C {qrepo} commit -m {shlex.quote(f'feat: {description[:72]}')}",
        tool="contribute_fix",
        args={"action": "git-commit", "branch": branch_name},
    )
    if commit.returncode != 0:
        run_audited(
            f"git -C {qrepo} checkout {shlex.quote(current_branch)}",
            tool="contribute_fix",
            args={"action": "restore-branch", "branch": current_branch},
        )
        return f"Failed to commit: {commit.stderr}"

    push = run_audited(
        f"git -C {qrepo} push -u origin {shlex.quote(branch_name)}",
        tool="contribute_fix",
        args={"action": "git-push", "branch": branch_name},
    )
    if push.returncode != 0:
        run_audited(
            f"git -C {qrepo} checkout {shlex.quote(current_branch)}",
            tool="contribute_fix",
            args={"action": "restore-branch", "branch": current_branch},
        )
        return f"Failed to push: {push.stderr}"

    pr_cmd = (
        f"gh pr create --repo {shlex.quote(_repo_slug())} "
        f"--title {shlex.quote(f'feat: {description[:60]}')} "
        f"--body {shlex.quote('## Summary\n\n' + description)} "
        f"--base {shlex.quote(base_branch)}"
    )
    pr_result = run_audited(
        pr_cmd,
        tool="contribute_fix",
        args={"action": "gh-pr-create", "branch": branch_name, "base": base_branch},
    )
    run_audited(
        f"git -C {qrepo} checkout {shlex.quote(current_branch)}",
        tool="contribute_fix",
        args={"action": "restore-branch", "branch": current_branch},
    )

    if pr_result.returncode != 0:
        return (
            f"Branch pushed but PR creation failed: {pr_result.stderr}\n"
            f"Manually create PR for branch '{branch_name}'."
        )
    return (
        f"PR created: {pr_result.stdout.strip()}\n\n"
        f"Branch: {branch_name}\n"
        f"Base: {base_branch}\n"
        f"Description: {description}"
    )


def list_improvements(state: str = "open") -> str:
    """List improvement suggestions (issues) for the repository."""
    result = run_command(
        f"gh issue list --repo {shlex.quote(_repo_slug())} --state {shlex.quote(state)} --limit 20"
    )
    if result.returncode != 0:
        return f"Failed to list issues: {result.stderr}"
    return result.stdout if result.stdout.strip() else "No issues found."


def list_pending_prs() -> str:
    """List open pull requests for the repository."""
    result = run_command(
        f"gh pr list --repo {shlex.quote(_repo_slug())} --state open --limit 20"
    )
    if result.returncode != 0:
        return f"Failed to list PRs: {result.stderr}"
    return result.stdout if result.stdout.strip() else "No open PRs."


def get_server_source(file_path: str) -> str:
    """Read source code of a file in the local bazzite-mcp repo."""
    base = Path(_repo_local()).resolve()
    target = (base / file_path).resolve()
    try:
        target.relative_to(base)
    except ValueError:
        return "File path must be inside the bazzite-mcp repository."

    if not target.exists() or not target.is_file():
        return f"File not found: {file_path}"
    return target.read_text(encoding="utf-8")
