from pathlib import Path
import shlex

from bazzite_mcp.config import load_config
from bazzite_mcp.runner import run_audited, run_command


def _repo_slug() -> str:
    return load_config().repo_slug


def _repo_local() -> str:
    return load_config().repo_local


def suggest_improvement(
    title: str,
    description: str,
    category: str = "enhancement",
) -> str:
    """Create a GitHub issue suggesting an improvement to bazzite-mcp."""
    labels = {
        "missing-tool": "enhancement,tool-request",
        "bug": "bug",
        "enhancement": "enhancement",
        "docs": "documentation",
        "guardrail": "safety",
    }
    label_str = labels.get(category, "enhancement")
    body = (
        f"**Category:** {category}\n\n{description}\n\n---\n"
        "*Auto-generated by bazzite-mcp self-improvement system*"
    )

    cmd = (
        f"gh issue create --repo {shlex.quote(_repo_slug())} "
        f"--title {shlex.quote(title)} "
        f"--body {shlex.quote(body)} "
        f"--label {shlex.quote(label_str)} 2>&1"
    )
    result = run_audited(
        cmd,
        tool="suggest_improvement",
        args={"title": title, "category": category},
    )
    if result.returncode != 0:
        return (
            "Could not create GitHub issue "
            f"(gh error: {result.stderr or result.stdout}).\n\n"
            "Suggestion recorded locally:\n"
            f"  Title: {title}\n"
            f"  Category: {category}\n"
            f"  Description: {description}"
        )

    return (
        f"Improvement suggested: {result.stdout.strip()}\n\n"
        f"Title: {title}\n"
        f"Category: {category}"
    )


def contribute_fix(branch_name: str, description: str, files_changed: str) -> str:
    """Create branch, commit selected files, push, and open PR."""
    repo = shlex.quote(_repo_local())

    create_branch = run_audited(
        f"git -C {repo} checkout -b {shlex.quote(branch_name)}",
        tool="contribute_fix",
        args={"branch": branch_name, "description": description[:100]},
    )
    if create_branch.returncode != 0:
        return f"Failed to create branch: {create_branch.stderr}"

    safe_files = " ".join(shlex.quote(f) for f in shlex.split(files_changed))
    add_result = run_command(f"git -C {repo} add {safe_files}")
    if add_result.returncode != 0:
        run_command(f"git -C {repo} checkout main")
        return f"Failed to stage files: {add_result.stderr}"

    commit = run_command(
        f"git -C {repo} commit -m {shlex.quote(f'feat: {description[:72]}')}"
    )
    if commit.returncode != 0:
        run_command(f"git -C {repo} checkout main")
        return f"Failed to commit: {commit.stderr}"

    push = run_command(f"git -C {repo} push -u origin {shlex.quote(branch_name)}")
    if push.returncode != 0:
        run_command(f"git -C {repo} checkout main")
        return f"Failed to push: {push.stderr}"

    pr_cmd = (
        f"gh pr create --repo {shlex.quote(_repo_slug())} "
        f"--title {shlex.quote(f'feat: {description[:60]}')} "
        f"--body {shlex.quote('## Summary\n\n' + description)} "
        "--base main"
    )
    pr_result = run_command(pr_cmd)
    run_command(f"git -C {repo} checkout main")

    if pr_result.returncode != 0:
        return (
            f"Branch pushed but PR creation failed: {pr_result.stderr}\n"
            f"Manually create PR for branch '{branch_name}'."
        )
    return (
        f"PR created: {pr_result.stdout.strip()}\n\n"
        f"Branch: {branch_name}\n"
        f"Description: {description}"
    )


def list_improvements(state: str = "open") -> str:
    """List improvement suggestions (issues) for the repository."""
    result = run_command(
        f"gh issue list --repo {shlex.quote(_repo_slug())} --state {shlex.quote(state)} --limit 20"
    )
    if result.returncode != 0:
        return f"Failed to list issues: {result.stderr}"
    return result.stdout if result.stdout.strip() else "No issues found."


def list_pending_prs() -> str:
    """List open pull requests for the repository."""
    result = run_command(
        f"gh pr list --repo {shlex.quote(_repo_slug())} --state open --limit 20"
    )
    if result.returncode != 0:
        return f"Failed to list PRs: {result.stderr}"
    return result.stdout if result.stdout.strip() else "No open PRs."


def get_server_source(file_path: str) -> str:
    """Read source code of a file in the local bazzite-mcp repo."""
    base = Path(_repo_local()).resolve()
    target = (base / file_path).resolve()
    try:
        target.relative_to(base)
    except ValueError:
        return "File path must be inside the bazzite-mcp repository."

    if not target.exists() or not target.is_file():
        return f"File not found: {file_path}"
    return target.read_text(encoding="utf-8")
